from .game import TOTAL_ITEMS
from .ui import MARGIN

WINDOW_NAME = "The Chamber Of Doubts"
PLAYER_NAME = "Abdullah"
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
PLAYER_NAME_SIZE = 30
HEALTHBAR_WIDTH = 250
HEALTHBAR_HEIGHT = 30
CONTROLPANEL_SIZE = 150
BUTTON_TO_PANEL_RATIO = 0.5
DISTANCE_FROM_CENTER = 0.3



SQUAREINVENTORY_CONTAINER_WIDTH = 65
SQUAREINVENTORY_CONTAINER_HEIGHT = 65
SQUAREINVENTORY_HEIGHT = SQUAREINVENTORY_CONTAINER_HEIGHT
SQUAREINVENTORY_WIDTH = TOTAL_ITEMS*SQUAREINVENTORY_CONTAINER_WIDTH+((TOTAL_ITEMS-1)*MARGIN)


CIRCULAR_INVENTORY_RADIUS = WINDOW_WIDTH*0.25